CREATE TABLE IF NOT EXISTS users (
  user_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_username TEXT,
  user_password  TEXT,
  user_emailAddress TEXT,
  user_bio VARCHAR(250),
  user_registrationDate DATE
);
CREATE INDEX ON users (id, user_username, user_emailAddress);