
spring:
   devtools:
      remote:
         secret: mysecret
   datasource:
      url: jdbc:postgresql://db:5432/user-service
      username: user-service
      password: user-service
   security:
      user:
         name: user
         password: password
   jpa:
      properties:
            hibernate:
               dialect: org.hibernate.dialect.PostgreSQLDialect